
export const builtIn = [{
  name: 'Sight Words (A)',
  cards: [
    { front: 'a' },
    { front: 'am' },
    { front: 'an' },
    { front: 'and' },
    { front: 'at' },
    { front: 'can' },
    { front: 'come' },
    { front: 'do' },
    { front: 'go' },
    { front: 'he' },
    { front: 'I' },
    { front: 'in' },
    { front: 'is' },
    { front: 'it' },
    { front: 'like' },
    { front: 'me' },
    { front: 'my' },
    { front: 'no' },
    { front: 'see' },
    { front: 'so' },
    { front: 'the' },
    { front: 'to' },
    { front: 'up' },
    { front: 'we' },
    { front: 'you' },
  ]
},
{
  name: 'Sight Words (B)',
  cards: [
    { front: 'all' },
    { front: 'am' },
    { front: 'are' },
    { front: 'as' },
    { front: 'away' },
    { front: 'back' },
    { front: 'be' },
    { front: 'bed' },
    { front: 'been' },
    { front: 'big' },
    { front: 'but' },
    { front: 'by' },
    { front: 'came' },
    { front: 'come' },
    { front: 'dad' },
    { front: 'day' },
    { front: 'did' },
    { front: 'dog' },
    { front: 'down' },
    { front: 'eat' },
    { front: 'five' },
    { front: 'for' },
    { front: 'four' },
    { front: 'get' },
    { front: 'girl' },
    { front: 'had' },
    { front: 'has' },
    { front: 'have' },
    { front: 'her' },
    { front: 'here' },
    { front: 'him' },
    { front: 'his' },
    { front: 'house' },
    { front: 'how' },
    { front: 'I\'m' },
    { front: 'if' },
    { front: 'into' },
    { front: 'like' },
    { front: 'little' },
    { front: 'live' },
    { front: 'look' },
    { front: 'make' },
    { front: 'man' },
    { front: 'mine' },
    { front: 'my' },
    { front: 'nine' },
    { front: 'now' },
    { front: 'of' },
    { front: 'one' },
    { front: 'or' },
    { front: 'our' },
    { front: 'out' },
    { front: 'play' },
    { front: 'put' },
    { front: 'run' },
    { front: 'said' },
    { front: 'saw' },
    { front: 'say' },
    { front: 'seven' },
    { front: 'she' },
    { front: 'sit' },
    { front: 'six' },
    { front: 'some' },
    { front: 'ten' },
    { front: 'than' },
    { front: 'that' },
    { front: 'the' },
    { front: 'them' },
    { front: 'there' },
    { front: 'three' },
    { front: 'us' },
    { front: 'very' },
    { front: 'wall' },
    { front: 'was' },
    { front: 'what' },
    { front: 'where' },
    { front: 'with' },
    { front: 'yes' },
    { front: 'you' },
    { front: 'your' },
  ]
},
{
  name: 'Sight Words (C)',
  cards: [
    { front: 'able' },
    { front: 'about' },
    { front: 'above' },
    { front: 'across' },
    { front: 'almost' },
    { front: 'any' },
    { front: 'anything' },
    { front: 'bad' },
    { front: 'ball' },
    { front: 'because' },
    { front: 'behind' },
    { front: 'black' },
    { front: 'blue' },
    { front: 'books' },
    { front: 'both' },
    { front: 'boy' },
    { front: 'bus' },
    { front: 'can\'t' },
    { front: 'car' },
    { front: 'city' },
    { front: 'down' },
    { front: 'end' },
    { front: 'fast' },
    { front: 'fish' },
    { front: 'fun' },
    { front: 'give' },
    { front: 'good' },
    { front: 'got' },
    { front: 'green' },
    { front: 'help' },
    { front: 'hide' },
    { front: 'hill' },
    { front: 'home' },
    { front: 'hit' },
    { front: 'jump' },
    { front: 'know' },
    { front: 'let' },
    { front: 'light' },
    { front: 'leave' },
    { front: 'love' },
    { front: 'month' },
    { front: 'much' },
    { front: 'name' },
    { front: 'new' },
    { front: 'orange' },
    { front: 'paper' },
    { front: 'place' },
    { front: 'purple' },
    { front: 'rain' },
    { front: 'ran' },
    { front: 'read' },
    { front: 'red' },
    { front: 'ride' },
    { front: 'room' },
    { front: 'sat' },
    { front: 'say' },
    { front: 'school' },
    { front: 'same' },
    { front: 'sky' },
    { front: 'sleep' },
    { front: 'small' },
    { front: 'something' },
    { front: 'stay' },
    { front: 'stop' },
    { front: 'take' },
    { front: 'tell' },
    { front: 'time' },
    { front: 'today' },
    { front: 'top' },
    { front: 'under' },
    { front: 'use' },
    { front: 'week' },
    { front: 'white' },
    { front: 'why' },
    { front: 'world' },
    { front: 'write' },
    { front: 'year' },
    { front: 'yell' },
    { front: 'yellow' },
    { front: 'yet' },
  ]
},
{
  name: 'Days of the Week',
  cards: [
    { front: 'Sunday' },
    { front: 'Monday' },
    { front: 'Tuesday' },
    { front: 'Wednesday' },
    { front: 'Thursday' },
    { front: 'Friday' },
    { front: 'Saturday' },
  ]
},
{
  name: 'Months',
  cards: [
    { front: 'January' },
    { front: 'February' },
    { front: 'March' },
    { front: 'April' },
    { front: 'May' },
    { front: 'June' },
    { front: 'July' },
    { front: 'August' },
    { front: 'September' },
    { front: 'October' },
    { front: 'November' },
    { front: 'December' },
  ]
}
];